#!/usr/bin/env python3
"""Does every event kind have a place that emits it?

On 2026-09-05 the host counted the call sites and found eleven of
twenty-nine kinds written and eighteen silent. The gap had no single cause
and needed none: every emitter was a local copy of the same seven lines, so
the mechanism was applied FROM MEMORY, and memory covers an arbitrary
subset. `demography.cpp` announced a vacated post on line 195 and created a
child on line 363 without a word.

So the list is taken from the ENUM and not from the code — walk the kinds
and ask which have a site, never the other way round — and it is a check in
the suite rather than a paragraph in a report. Eighteen holes did not appear
at once; they accumulated one at a time, and without a roll-call they will
accumulate again.

A kind may be silent ON PURPOSE. That is declared in the header, on the kind
itself, as `@no_emit <reason>` — the reason is the point: `// not emitted`
says only what is already visible from the absence.

AND THE ANSWER IS PUBLISHED, because a consumer needs it and a comment is
not something a consumer can read (boss, 2026-09-07). `host` grew a check for
"a door the document promises and the dispatch does not dispatch", and it
found a third kind nobody had named: a name present on BOTH sides whose event
never arrives. Its own check had to read `@no_emit` — a COMMENT in our
header — and it said the limit honestly: the core can stop raising a kind and
never touch the comment, and nothing would see it.

  We walk the code and know the real answer. It reads the prose and knows the
  promised one. They part company in silence, and the first to notice is the
  scene author who waits half a year for an event.

So `--export` writes tables/event_sites.csv: the kind, whether a site exists,
and the waiver reason. Regenerated and CHECKED on every run, so the file
cannot drift from the walk the way the comment drifted from the code.

WHAT THE COLUMN DOES NOT SAY, and the name is chosen to keep it from
pretending. `has_site` means "somewhere in the sources a line raises this
kind". It does NOT mean the event arrives: a site can sit in a branch
execution never enters, which is the same distinction the architecture makes
between a check that exists and a check that runs. The rung above this one —
counting subscriptions that actually fired — belongs to whoever runs the
world, and `host` keeps it.
"""

import os
import re
import sys

CORE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HEADER = os.path.join(CORE, "include", "core_common", "event_state.h")
SOURCE_DIRS = [os.path.join(CORE, "subprojects")]

# The one function that appends to the outbox (core_common/emit_event.h). A
# file that emits calls it; a file that only reads kinds does not, which is
# what separates an emitter from the boundary's mirror.
EMITTER_CALL = "EmitEvent("


def kinds_and_waivers():
    """Every EventKind value in declaration order, plus its @no_emit reason."""
    text = open(HEADER, encoding="utf-8").read()
    body = text[text.index("enum class EventKind"):]
    body = body[:body.index("kEventKindCount")]
    found = []
    pending_waiver = None
    for line in body.splitlines():
        waiver = re.search(r"@no_emit\s+(.+)", line)
        if waiver:
            pending_waiver = waiver.group(1).strip()
            continue
        name = re.match(r"\s*(k[A-Za-z0-9]+)\s*(=|,)", line)
        if name:
            if name.group(1) != "kNone":
                found.append((name.group(1), pending_waiver))
            pending_waiver = None
    return found


def emitting_files():
    """Files that call the emitter, mapped to the kinds they name."""
    sites = {}
    for root_dir in SOURCE_DIRS:
        for root, _dirs, files in os.walk(root_dir):
            for name in files:
                if not name.endswith((".cpp", ".h", ".inl")):
                    continue
                path = os.path.join(root, name)
                text = open(path, encoding="utf-8", errors="ignore").read()
                if EMITTER_CALL not in text:
                    continue
                for kind in set(re.findall(r"EventKind::(k[A-Za-z0-9]+)", text)):
                    if kind in ("kNone", "kEventKindCount"):
                        continue
                    sites.setdefault(kind, []).append(os.path.relpath(path, CORE))
    return sites


def export_rows(kinds, sites):
    """The walk's answer as data: one row per kind, in declaration order."""
    rows = ["# generated by scripts/event_sites.py — do not edit by hand",
            "# has_site=1: a line somewhere in subprojects/ raises this kind through",
            "# EmitEvent. It does NOT mean the event arrives — a site can sit in a",
            "# branch execution never enters. Counting what actually fired is the rung",
            "# above this one and belongs to whoever runs the world.",
            "# no_emit_reason: non-empty when the header declares the silence deliberate.",
            "kind,has_site,no_emit_reason"]
    for kind, waiver in kinds:
        reason = (waiver or "").replace('"', "'")
        quoted = f'"{reason}"' if "," in reason else reason
        rows.append(f"{kind},{1 if kind in sites else 0},{quoted}")
    return "\n".join(rows) + "\n"


EXPORT = os.path.join(CORE, "tables", "event_sites.csv")


def main() -> int:
    kinds = kinds_and_waivers()
    sites = emitting_files()

    # THE EXPORT IS CHECKED ON EVERY RUN, not only written on request. A file
    # that is refreshed when somebody remembers is a second home for the fact,
    # and the whole reason it exists is that the first home — a comment — went
    # stale without a sound.
    wanted = export_rows(kinds, sites)
    if "--export" in sys.argv:
        with open(EXPORT, "w", encoding="utf-8") as handle:
            handle.write(wanted)
        print(f"выгружено: {os.path.relpath(EXPORT, CORE)}")
    else:
        have = open(EXPORT, encoding="utf-8").read() if os.path.exists(EXPORT) else ""
        if have != wanted:
            print("ОТСТАЛА ВЫГРУЗКА: tables/event_sites.csv не совпадает с обходом кода.")
            print("починка: python3 scripts/event_sites.py --export")
            return 1
    missing = []
    waived = []
    for kind, waiver in kinds:
        if kind in sites:
            if waiver:
                # A kind that is BOTH waived and emitted is a contradiction
                # worth failing on: one of the two is out of date, and which
                # one is a question for whoever reads this.
                print(f"КОНФЛИКТ: {kind} помечен @no_emit «{waiver}», но место вызова есть")
                missing.append(kind)
            continue
        if waiver:
            waived.append((kind, waiver))
        else:
            missing.append(kind)

    for kind, waiver in waived:
        print(f"  молчит по причине  {kind:22s} {waiver}")
    for kind in missing:
        print(f"  НЕТ МЕСТА ВЫЗОВА   {kind}")
    print(f"EVENT_KINDS={len(kinds)} WITH_SITE={len(sites)} "
          f"WAIVED={len(waived)} MISSING={len(missing)}")
    if missing:
        print("починка: место вызова там, где предмет случается, через EmitEvent;")
        print("         намеренное молчание — @no_emit с причиной в event_state.h")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
